# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

      
    - name: Build with Gradle
      run: ./gradlew build additionalCopy
      env:
        BUILD_RELEASE: ${{ github.event.prerelease == false }}
    
    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'build/to_upload/*'
        # secrets.GITHUB_TOKEN
        repo-token: ${{ secrets.GITHUB_TOKEN }}
